### ISSUE TITLE
Feature: include extra jobs

### ISSUE THREAD

**Issue by andreacampi** [miracle2k/tarsnapper#2]
Tarsnapper is extremely useful, thanks!

I would find it very convenient if there were a way to specify job in separate files, something like:

    # Global values, valid for all jobs unless overridden:
    deltas: 1d 7d 30d
    target: /localmachine/$name-$date
    extra_jobs: /usr/local/etc/tarsnapper/extra/*
   
    jobs:
      # some jobs

and then have one or more jobs per file in the given directory.

The rationale for this is, I use Chef and I have created my own tarsnap cookbooks.
This feature would make it easy for other recipes (e.g. a database) to configure their jobs, which would get picked up automatically.

I would send a pull request but my knowledge of Python is next to 0 :)

**Comment by jeffwidman** [comment]
I would also appreciate this for some Ansible scripts. 

If you're willing to add an extra dependency, incorporating [the yamlreader library](https://github.com/ImmobilienScout24/yamlreader#use-it-in-your-software) looks like it would provide this functionality very easily... @miracle2k would you open to a PR on this?

**Comment by miracle2k** [comment]
I don't mind a dependency, though on first look maybe yamlreader is not flexible enough. Ideally we'd support globs. We might be able to adopt their code though.

I would merge a PR, for sure.
