### ISSUE TITLE
Dates with timezone offsets cannot be parsed (at least under OS X and FreeBSD)

### ISSUE THREAD

**Issue by dneades** [miracle2k/tarsnapper#21]
I have tarsnap archives with the dates formatted like this:

> hg-2015-01-27T19:34:01+0000

One might expect these to be parsed correctly with a suitable --dateformat argument, e.g.

> tarsnapper --target "hg-\$date" --dateformat "%Y-%m-%dT%H:%M:%S%z" --deltas 1h 1d 7d 30d - expire --dry-run

However, this does not work (at least under OS X Yosemite using Homebrew’s Python 2.7.9 and FreeBSD 9.3 with Python 2.7.9), as Python 2.7.9’s datetime.strptime does not recognize the %z strftime format conversion specification. (Note, however, that Python 3.4.2’s strptime on the same platforms *does* support %z.)

It would thus be helpful if tarsnapper were to parse dates using a mechanism that supported timezone offsets in a platform-independent way, or if tarsnapper were to be available in a version that could run under Python 3.

As a workaround, if the timezone offset never changes, one can specify the offset as part of the target, like this:

> tarsnapper --target "hg-\$date+0000" --dateformat "%Y-%m-%dT%H:%M:%S" --deltas 1h 1d 7d 30d - expire --dry-run

However, this solution obviously cannot be used where the timezone offset varies.

**Comment by miracle2k** [comment]
It seems to me that we should just use python-dateutil, as the readme claims, as you point out in #20. 

If --dateformat is specified, it will be used with strptime, and when in the future tarsnapper runs on Python 3, that will get %z support that.

**Comment by dneades** [comment]
Thank you for the response, much appreciated. (And, thank you for Tarsnapper :-)

I don’t have any direct experience with python-dateutil, but it does look like a plausible solution from its documentation. If --dateformat continues to use strptime as you suggest, then that would give the best of both worlds (and, at least, be no worse than the present situation). So yes, that sounds good :-)

Thanks again.
