### ISSUE TITLE
Automating backups via cron - is tarsnapper the tool for it?

### ISSUE THREAD

**Issue by NielsH** [miracle2k/tarsnapper#27]
Hi there,

I'd like to set up a backup schema via tarsnap that creates the backups on a certain interval and deletes the old ones according to the defined scheme.

So I created the following config file:
```
deltas: 1h 6h 1d 7d 24d 180d
target: $name-$date

jobs:
  image:
     source: /
```

Now, it works well by calling it manually, but from the readme i'm having some issues with understanding how to actually automate it.

The Readme says:
```The ability to expire old backups using a Grandfather-father-son backup scheme. This feature can be used in conjunction with tarsnapper backup jobs, or standalone, to be applied to any existing set of tarsnap backup archives, regardless of how they have been created.```

Am I understanding it correctly that I can just cron 1 command and it'll create a new backup and then check the settings to see if some old backups can be removed (and if so, remove them)?
I've tried: `tarsnapper -c /usr/local/etc/tarsnap-cron.conf make,expire` but that doesn't work, as I can only do -or- make, -or- expire. Does that mean I need 2 crons?

Having tried it with a cron that just ran every minute or every 5 minutes, it does create a new backup every 1/5 minutes. However what I need it to do is check the deltas settings, and then only create a new backup if it is needed (so based on the above, if 1h passed since the previous backup).
Is that possible via tarsnapper, or do I have to configure the cron based on the frequency I want backups to run?

Perhaps I'm missing something here, but I can't find all that much online either for using tarsnapper to automate crons in this way, especially not using crons.

Thank you in advance!
Niels

**Comment by miracle2k** [comment]
The "make" command expires backups too (see --help).

**Comment by NielsH** [comment]
That's great - thank you.

For actually automating, what's the best practice to run this? With this scheme:
`deltas: 1h 6h 1d 7d 24d 180d`
if I run tarsnapper make 1x per hour it'll take care of things?

**Comment by miracle2k** [comment]
The expire feature tries to do a reasonable job regardless of the backup frequency, but yes, it makes sense to run it as often as your smallest interval.
