### ISSUE TITLE
Feature Request: add --no-expire

### ISSUE THREAD

**Issue by rbauduin** [miracle2k/tarsnapper#38]
I'd like to user tarsnapper from cron without expiration because the keyfile has no delete access, and the deletion key is passphrased. Then I could run the -expire manually interactively with the passphrased key using the same configuration.

**Comment by miracle2k** [comment]
That flag should exists: ` tarsnapper make --help`.

If you don't see the flag there, make sure you are using the latest version - potentially the one from Github.
